CREATE TABLE TIL_PORTFOLIO_PROJECTS.CHARALAMBOS.LEGO_COLOURS(
ID INTEGER,
NAME VARCHAR(28),
RGB VARCHAR(6),
IS_TRANS VARCHAR(1)
);

CREATE TABLE TIL_PORTFOLIO_PROJECTS.CHARALAMBOS.LEGO_INVENTORIES(
ID INTEGER,
VERSION INTEGER,
SET_NUM VARCHAR(16)
);

CREATE TABLE TIL_PORTFOLIO_PROJECTS.CHARALAMBOS.LEGO_INVENTORY_PARTS(
INVENTORY_ID INTEGER,
PART_NUM VARCHAR(15),
COLOUR_ID INTEGER,
QUANTITY INTEGER,
IS_SPARE VARCHAR(1)
);

CREATE TABLE TIL_PORTFOLIO_PROJECTS.CHARALAMBOS.LEGO_INVENTORY_SETS1(
INVENTORY_ID INTEGER,
SET_NUM VARCHAR(16),
QUANTITY INTEGER
);

ALTER TABLE TIL_PORTFOLIO_PROJECTS.CHARALAMBOS.LEGO_INVENTORY_SETS1 RENAME TO TIL_PORTFOLIO_PROJECTS.CHARALAMBOS.LEGO_INVENTORY_SETS;

CREATE TABLE TIL_PORTFOLIO_PROJECTS.CHARALAMBOS.LEGO_PARTS(
PART_NUM VARCHAR(15),
NAME VARCHAR(223),
PART_CAT_ID INTEGER
);

CREATE TABLE TIL_PORTFOLIO_PROJECTS.CHARALAMBOS.LEGO_PART_CATEGORIES(
ID INTEGER,
NAME VARCHAR(44)
);

CREATE TABLE TIL_PORTFOLIO_PROJECTS.CHARALAMBOS.LEGO_SETS(
SET_NUM VARCHAR(16),
NAME VARCHAR(95),
YEAR INTEGER,
THEME_ID INTEGER,
NUM_PARTS INTEGER
);

CREATE TABLE TIL_PORTFOLIO_PROJECTS.CHARALAMBOS.LEGO_THEMES(
ID INTEGER,
NAME VARCHAR(32),
PARENT_ID INTEGER
);


INSERT INTO TIL_PORTFOLIO_PROJECTS.CHARALAMBOS.LEGO_COLOURS(
SELECT *
FROM TIL_PORTFOLIO_PROJECTS.STAGING.LEGO_COLORS
);

INSERT INTO TIL_PORTFOLIO_PROJECTS.CHARALAMBOS.LEGO_INVENTORIES(
SELECT *
FROM TIL_PORTFOLIO_PROJECTS.STAGING.LEGO_INVENTORIES
);


INSERT INTO TIL_PORTFOLIO_PROJECTS.CHARALAMBOS.LEGO_INVENTORY_PARTS(
SELECT *
FROM TIL_PORTFOLIO_PROJECTS.STAGING.LEGO_INVENTORY_PARTS
);

INSERT INTO TIL_PORTFOLIO_PROJECTS.CHARALAMBOS.LEGO_INVENTORY_SETS(
SELECT *
FROM TIL_PORTFOLIO_PROJECTS.STAGING.LEGO_INVENTORY_SETS
);

INSERT INTO TIL_PORTFOLIO_PROJECTS.CHARALAMBOS.LEGO_PARTS(
SELECT *
FROM TIL_PORTFOLIO_PROJECTS.STAGING.LEGO_PARTS
);

INSERT INTO TIL_PORTFOLIO_PROJECTS.CHARALAMBOS.LEGO_PART_CATEGORIES(
SELECT *
FROM TIL_PORTFOLIO_PROJECTS.STAGING.LEGO_PART_CATEGORIES
);

INSERT INTO TIL_PORTFOLIO_PROJECTS.CHARALAMBOS.LEGO_SETS(
SELECT *
FROM TIL_PORTFOLIO_PROJECTS.STAGING.LEGO_SETS
);

INSERT INTO TIL_PORTFOLIO_PROJECTS.CHARALAMBOS.LEGO_THEMES(
SELECT *
FROM TIL_PORTFOLIO_PROJECTS.STAGING.LEGO_THEMES
);

SELECT COUNT(  INVENTORY_ID)
FROM TIL_PORTFOLIO_PROJECTS.CHARALAMBOS.LEGO_INVENTORY_PARTS;

SELECT COUNT( DISTINCT ID)
FROM TIL_PORTFOLIO_PROJECTS.CHARALAMBOS.LEGO_INVENTORIES;

ALTER TABLE TIL_PORTFOLIO_PROJECTS.CHARALAMBOS.LEGO_SETS ADD PRIMARY KEY (SET_NUM);
ALTER TABLE TIL_PORTFOLIO_PROJECTS.CHARALAMBOS.LEGO_INVENTORIES ADD PRIMARY KEY (ID);
ALTER TABLE TIL_PORTFOLIO_PROJECTS.CHARALAMBOS.LEGO_COLOURS ADD PRIMARY KEY (ID);
ALTER TABLE TIL_PORTFOLIO_PROJECTS.CHARALAMBOS.LEGO_PARTS ADD PRIMARY KEY(PART_NUM);
ALTER TABLE TIL_PORTFOLIO_PROJECTS.CHARALAMBOS.LEGO_PART_CATEGORIES ADD PRIMARY KEY(ID);
ALTER TABLE TIL_PORTFOLIO_PROJECTS.CHARALAMBOS.LEGO_THEMES ADD PRIMARY KEY(ID);






ALTER TABLE TIL_PORTFOLIO_PROJECTS.CHARALAMBOS.LEGO_INVENTORY_SETS ADD FOREIGN KEY (SET_NUM) REFERENCES TIL_PORTFOLIO_PROJECTS.CHARALAMBOS.LEGO_SETS(SET_NUM);
ALTER TABLE TIL_PORTFOLIO_PROJECTS.CHARALAMBOS.LEGO_INVENTORY_SETS ADD FOREIGN KEY (INVENTORY_ID) REFERENCES 
TIL_PORTFOLIO_PROJECTS.CHARALAMBOS.LEGO_INVENTORIES (ID);
ALTER TABLE TIL_PORTFOLIO_PROJECTS.CHARALAMBOS.LEGO_INVENTORY_PARTS ADD FOREIGN KEY (COLOUR_ID) REFERENCES
TIL_PORTFOLIO_PROJECTS.CHARALAMBOS.LEGO_COLOURS(ID);
ALTER TABLE TIL_PORTFOLIO_PROJECTS.CHARALAMBOS.LEGO_INVENTORY_PARTS ADD FOREIGN KEY (PART_NUM) REFERENCES
TIL_PORTFOLIO_PROJECTS.CHARALAMBOS.LEGO_PARTS(PART_NUM);
ALTER TABLE TIL_PORTFOLIO_PROJECTS.CHARALAMBOS.LEGO_PARTS ADD FOREIGN KEY (PART_CAT_ID) REFERENCES
TIL_PORTFOLIO_PROJECTS.CHARALAMBOS.LEGO_PART_CATEGORIES(ID);
ALTER TABLE TIL_PORTFOLIO_PROJECTS.CHARALAMBOS.LEGO_SETS ADD FOREIGN KEY (THEME_ID) REFERENCES
TIL_PORTFOLIO_PROJECTS.CHARALAMBOS.LEGO_THEMES(ID);
ALTER TABLE TIL_PORTFOLIO_PROJECTS.CHARALAMBOS.LEGO_INVENTORY_PARTS ADD FOREIGN KEY (INVENTORY_ID) REFERENCES
TIL_PORTFOLIO_PROJECTS.CHARALAMBOS.LEGO_INVENTORIES (ID);

SELECT *
FROM TIL_PORTFOLIO_PROJECTS.INFORMATION_SCHEMA.APPLICABLE_ROLES;