With DATA1 as(
select *
from
(select
MOBILE_VAL,CUSTOMER_ID as CUSTOMERA,
split_part(Type,'___',2) as Type3,
CASE
when Type3 = 'OVERALL_RATING' then 1 
else 0 end as Flag
from TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK06_DSB_CUSTOMER_SURVEY

UNPIVOT(
MOBILE_VAL for Type
IN("MOBILE_APP___EASE_OF_USE","MOBILE_APP___EASE_OF_ACCESS","MOBILE_APP___NAVIGATION","MOBILE_APP___LIKELIHOOD_TO_RECOMMEND","MOBILE_APP___OVERALL_RATING")
  ) 
WHERE Flag = 0) as a

INNER JOIN

(
select 
ONLINE_VAL,CUSTOMER_ID as CUSTOMERB,
split_part(Type,'___',2) as Type2,split_part(Type,'-',1) as Type1,
CASE
when Type1 = 'OVERALL_RATING' then 1 
else 0 end as Flag1
from TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK06_DSB_CUSTOMER_SURVEY

UNPIVOT

(ONLINE_VAL for Type
 IN ("ONLINE_INTERFACE___EASE_OF_USE","ONLINE_INTERFACE___EASE_OF_ACCESS","ONLINE_INTERFACE___NAVIGATION","ONLINE_INTERFACE___LIKELIHOOD_TO_RECOMMEND",
 "ONLINE_INTERFACE___OVERALL_RATING")

)  
WHERE Flag1 = 0
) as b

ON b.CUSTOMERB = a.CUSTOMERA
and b.Type2 = a.Type3

)

SELECT ROUND((COUNT(CUSTOMERB)/(SELECT COUNT(DISTINCT CUSTOMERB) FROM DATA1 )*100),1) AS PERCENT_BY_FAN,FAN_CATEGORY
FROM(
SELECT AVG(ONLINE_VAL)-AVG(MOBILE_VAL) AS DIFFOFAVG,CUSTOMERB,
CASE
WHEN DIFFOFAVG >= 2 Then 'Online Superfan'
WHEN DIFFOFAVG >= 1 and DIFFOFAVG < 2 then 'Online Fan'
WHEN DIFFOFAVG <= -2 Then 'Mobile Superfan'
WHEN DIFFOFAVG <= -1 and DIFFOFAVG > -2 then 'Mobile Fan'
WHEN DIFFOFAVG >= 0 and DIFFOFAVG <1 then 'Neutral'
else 'Neutral' end as FAN_CATEGORY
FROM DATA1
GROUP BY CUSTOMERB)
GROUP BY FAN_CATEGORY