SELECT DISTINCT
CAST("'Date of Birth'" as DATE) as Date_of_Birth,
"'Ethnicity'" as Ethnicity,
"'Account Type'" as Account_Type,
ID,
FIRST_VALUE(JOINING_DATE) OVER (PARTITION BY DATE_OF_BIRTH,
Ethnicity,
Account_Type,
ID ORDER BY JOINING_DATE ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING)

FROM(
SELECT *,
'2023'as year,
'04'as month,
TO_DATE(year||month||CAST(JOINING_DAY AS VARCHAR(255)), 'YYYYMMDD') AS JOINING_DATE


FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK04_APRIL

UNION ALL

SELECT *,
'2023'as year,
'08'as month,
TO_DATE(year||month||CAST(JOINING_DAY AS VARCHAR(255)), 'YYYYMMDD') AS JOINING_DATE
FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK04_AUGUST

UNION ALL

SELECT *,
'2023'as year,
'12'as month,
TO_DATE(year||month||CAST(JOINING_DAY AS VARCHAR(255)), 'YYYYMMDD') AS JOINING_DATE
FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK04_DECEMBER

UNION ALL

SELECT *,
'2023'as year,
'02'as month,
TO_DATE(year||month||CAST(JOINING_DAY AS VARCHAR(255)), 'YYYYMMDD') AS JOINING_DATE
FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK04_FEBRUARY

UNION ALL

SELECT *,
'2023'as year,
'01'as month,
TO_DATE(year||month||CAST(JOINING_DAY AS VARCHAR(255)), 'YYYYMMDD') AS JOINING_DATE
FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK04_JANUARY

UNION ALL

SELECT *,
'2023'as year,
'07'as month,
TO_DATE(year||month||CAST(JOINING_DAY AS VARCHAR(255)), 'YYYYMMDD') AS JOINING_DATE
FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK04_JULY

UNION ALL

SELECT *,
'2023'as year,
'06'as month,
TO_DATE(year||month||CAST(JOINING_DAY AS VARCHAR(255)), 'YYYYMMDD') AS JOINING_DATE
FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK04_JUNE

UNION ALL

SELECT *,
'2023'as year,
'03'as month,
TO_DATE(year||month||CAST(JOINING_DAY AS VARCHAR(255)), 'YYYYMMDD') AS JOINING_DATE
FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK04_MARCH

UNION ALL

SELECT *,
'2023'as year,
'05'as month,
TO_DATE(year||month||CAST(JOINING_DAY AS VARCHAR(255)), 'YYYYMMDD') AS JOINING_DATE
FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK04_MAY

UNION ALL

SELECT *,
'2023'as year,
'11'as month,
TO_DATE(year||month||CAST(JOINING_DAY AS VARCHAR(255)), 'YYYYMMDD') AS JOINING_DATE
FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK04_NOVEMBER

UNION ALL

SELECT *,
'2023'as year,
'10'as month,
TO_DATE(year||month||CAST(JOINING_DAY AS VARCHAR(255)), 'YYYYMMDD') AS JOINING_DATE
FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK04_OCTOBER

UNION ALL

SELECT *,
'2023'as year,
'09'as month,
TO_DATE(year||month||CAST(JOINING_DAY AS VARCHAR(255)), 'YYYYMMDD') AS JOINING_DATE
FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK04_SEPTEMBER
)

PIVOT(
max(value) for demographic IN('Date of Birth','Ethnicity','Account Type')
)

