SELECT TRANSACT,ACCOUNT_TO,TRANSACTION_DATE,VALUE,
ACCOUNT_NUMBER,ACCOUNT_TYPE,BALANCE_DATE,BALANCE,NAME,
DATE_OF_BIRTH,PHONE_NUMBER,FIRST_LINE_OF_ADDRESS,VAL
FROM
(SELECT *
FROM
(SELECT *, '0'||CONTACT_NUMBER AS PHONE_NUMBER
FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK07_ACCOUNT_HOLDERS
WHERE ACCOUNT_HOLDER_ID IS NOT NULL) AS B

INNER JOIN 

(SELECT VALUE AS VAL, ACCOUNT_NUMBER,ACCOUNT_TYPE,ACCOUNT_HOLDER_ID,BALANCE_DATE,BALANCE
FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK07_ACCOUNT_INFORMATION,
LATERAL SPLIT_TO_TABLE(ACCOUNT_HOLDER_ID,', ')) AS A

ON B.ACCOUNT_HOLDER_ID = VAL

INNER JOIN 


(SELECT TRANSACTION_ID AS TRANSACT, ACCOUNT_FROM, ACCOUNT_TO
FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK07_TRANSACTION_PATH) AS C

ON  ACCOUNT_NUMBER = ACCOUNT_FROM

INNER JOIN 

TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK07_TRANSACTION_DETAIL AS D

ON D.TRANSACTION_ID = TRANSACT)
WHERE VALUE > 1000 AND ACCOUNT_TYPE != 'Platinum' AND CANCELLED_ = 'N' ;