SELECT ONLINE_OR_IN_PERSON,
TOTAL_AMOUNT,
QUARTER2,
TARGET_VALUE,
TOTAL_AMOUNT - TARGET_VALUE AS VARIANCE_TO_TARGET
FROM (
SELECT *
FROM(
SELECT 
SPLIT_PART(TRANSACTION_CODE,'-',1) AS BANK,
CASE
WHEN ONLINE_OR_IN_PERSON = 1 THEN 'Online'
ELSE 'In-Person'
END AS ONLINE_OR_IN_PERSON,
DATE_PART('QUARTER',TO_DATE(SPLIT_PART(TRANSACTION_DATE,' ',1),'DD/MM/YYYY')) AS QUARTER,
SUM(VALUE) AS TOTAL_AMOUNT
FROM 
TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK01
WHERE BANK = 'DSB'
GROUP BY ONLINE_OR_IN_PERSON,BANK,QUARTER)
AS A

INNER JOIN

(
SELECT 
CAST(REPLACE(QUARTER2,'Q','') AS NUMBER(38)) AS QUARTER2,
TARGET_VALUE,
ONLINE_OR_IN_PERSON AS ONPE
FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK03_TARGETS

UNPIVOT(
TARGET_VALUE FOR QUARTER2
IN(Q1,Q2,Q3,Q4)
)) AS B

ON A.QUARTER = B.QUARTER2 AND A.ONLINE_OR_IN_PERSON = B.ONPE
)
