WITH TE AS(

SELECT *,'01' AS MONTH
FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK08_01

UNION ALL 

SELECT *, '02'
FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK08_02

UNION ALL 

SELECT *, '03'
FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK08_03

UNION ALL

SELECT *, '04'
FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK08_04

UNION ALL 

SELECT *, '05'
FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK08_05

UNION ALL

SELECT *, '06'
FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK08_06

UNION ALL

SELECT *, '07'
FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK08_07

UNION ALL

SELECT *, '08'
FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK08_08

UNION ALL

SELECT *, '09'
FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK08_09

UNION ALL 

SELECT *, '10'
FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK08_10

UNION ALL 

SELECT *, '11'
FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK08_11

UNION ALL

SELECT *, '12'
FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK08_12

)
SELECT MARKET_CAP_CATEGORIES,PURCHASE_PRICE_GROUPINGS,TO_DATE('01'||MONTH||'2023','DDMMYYYY') AS FILE_DATE, TICKER,SECTOR,MARKET,STOCK_NAME,MARKET_CAP_NUMBER,NEW_PURCHASE_PRICE,RANK
FROM(
SELECT *, 

CAST(LTRIM(PURCHASE_PRICE,'$') AS FLOAT) AS NEW_PURCHASE_PRICE,
CASE 
WHEN NEW_PURCHASE_PRICE >=0 AND NEW_PURCHASE_PRICE < 25000 THEN 'LOW'
WHEN NEW_PURCHASE_PRICE >= 25000 AND NEW_PURCHASE_PRICE <50000 THEN 'MEDIUM'
WHEN NEW_PURCHASE_PRICE >= 50000 AND NEW_PURCHASE_PRICE < 75000 THEN 'HIGH'
WHEN NEW_PURCHASE_PRICE >= 75000 AND NEW_PURCHASE_PRICE < 100000 THEN 'VERY HIGH'
ELSE 'NULL' END AS PURCHASE_PRICE_GROUPINGS,

CASE 

WHEN CONTAINS(MARKET_CAP,'M') THEN CAST(LTRIM(REGEXP_REPLACE(MARKET_CAP, '[A-Z]',''),'$') AS FLOAT) *1000000
WHEN CONTAINS(MARKET_CAP,'B') THEN CAST(LTRIM(REGEXP_REPLACE(MARKET_CAP, '[A-Z]',''),'$') AS FLOAT) *1000000000
ELSE 0 END MARKET_CAP_NUMBER,

CASE 

WHEN MARKET_CAP_NUMBER < 100000000 THEN 'SMALL'
WHEN MARKET_CAP_NUMBER >= 100000000 AND MARKET_CAP_NUMBER < 1000000000 THEN 'MEDIUM' 
WHEN MARKET_CAP_NUMBER >= 1000000000 AND MARKET_CAP_NUMBER < 100000000000 THEN 'LARGE'
ELSE 'HUGE' END AS MARKET_CAP_CATEGORIES,

RANK() OVER (PARTITION BY MONTH,PURCHASE_PRICE_GROUPINGS ,MARKET_CAP_CATEGORIES ORDER BY NEW_PURCHASE_PRICE DESC) AS RANK
 

FROM TE
WHERE MARKET_CAP != 'n/a')

HAVING RANK < 6